name: "Prusa Connect RTSP"
description: "A simple video translator for Prusa Connect."
version: "0.1.3"
slug: "prusa_conncect_rtsp_homeassistant"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  CAMERA_URLS: []
  TOKENS: []
  FRAME_CAPTURE_DELAY: 1
  CAMERA_CYCLE_DELAY: 10
  CONNECTION_TIMEOUT_DELAY: 5
schema:
  CAMERA_URLS:
    - url
  TOKENS:
    - password
  FRAME_CAPTURE_DELAY: float
  CAMERA_CYCLE_DELAY: float
  CONNECTION_TIMEOUT_DELAY: float
  log_level: list(debug|info|warning|error|critical)
